# Generated by Django 4.0.4 on 2022-05-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('countryOption', models.CharField(max_length=255)),
                ('cityOption', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),                
                ('join', models.CharField(max_length=255)),                
                ('status', models.CharField(max_length=255)),                
                ('image', models.TextField(null=True)),                
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
