# Generated by Django 4.0.6 on 2022-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
